version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev --db postgres --db-url-host keycloak-db --db-username keycloak --db-password keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

#  react-ui:
#    image: node:18-alpine
#    command: sh -c "npm install && npm start"
#    working_dir: /app
#    volumes:
#      - ./react-ui:/app
#    ports:
#      - "3000:3000"
#    environment:
#      REACT_APP_KEYCLOAK_URL: http://localhost:8080kkkkkkkkkkkkkkk
#    depends_on:
#      - keycloak
#
  spring-api:
    build:
      context: ./spring-api
    ports:
      - "8081:8081"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - keycloak

volumes:
  keycloak_data: