version: '3.8'

services:
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev --db postgres --db-url-host keycloak-db --db-username keycloak --db-password keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db

  #  react-ui:
  #    image: saurabh896/keycloak-frontend:latest
  #    container_name: keycloak-frontend
  #    ports:
  #      - "${REACT_PORT}:80"
  #    environment:
  #      REACT_APP_KEYCLOAK_URL: http://keycloak:8080
  #    depends_on:
  #      - keycloak

  spring-api:
    image: saurabh896/keycloak-backend:latest
    container_name: keycloak-backend
    ports:
      - "${SPRING_PORT}:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://keycloak-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - keycloak

volumes:
  keycloak_data: